version: '2'

services:
  proxy:
    #image: scarry92/proxy-faker
    build: .
    ports:
      - "80:80"
    volumes:
      #for windows- c:/dev/projects/proxy-faker:/usr/src/proxy
      - /home/scarry-dev/dev/projects/proxy-faker:/usr/src/proxy
    networks:
          static-network:
            ipv4_address: 172.20.128.2
    entrypoint: npm start

networks:
  static-network:
      ipam:
        config:
          - subnet: 172.20.0.0/16
            ip_range: 172.28.5.0/24